export const rows = [
  {
    id: 1,
    name: "Hager",
    email: "test@gmail.com",
    age: "20",
    phone: "0123456789",
    access: "user",
  },
  {
    id: 2,
    name: "Ahmed",
    email: "test@gmail.com",
    age: "31",
    phone: "0123456789",
    access: "Manager",
  },
  {
    id: 3,
    name: "Shehab",
    email: "test@gmail.com",
    age: "30",
    phone: "0123456789",
    access: "Manager",
  },
  {
    id: 4,
    name: "Mohsen",
    email: "test@gmail.com",
    age: "22",
    phone: "0123456789",
    access: "user",
  },
  {
    id: 5,
    name: "Abdelrahman",
    email: "test@gmail.com",
    age: "50",
    phone: "0123456789",
    access: "Admin",
  },
  {
    id: 6,
    name: "Hello",
    email: "test@gmail.com",
    age: "28",
    phone: "0123456789",
    access: "Manager",
  },
  {
    id: 7,
    name: "Abdelrahman",
    email: "test@gmail.com",
    age: "6",
    phone: "0123456789",
    access: "Admin",
  },
  {
    id: 8,
    name: "Abdelrahman",
    email: "test@gmail.com",
    age: "20",
    phone: "0123456789",
    access: "user",
  },
  {
    id: 9,
    name: "Abdelrahman",
    email: "test@gmail.com",
    age: "80",
    phone: "0123456789",
    access: "Manager",
  },
];


